name: LogTPS
version: ${project.plugin_version}
description: Sends server TPS and MSPT to the player

author: Totorewa

api-version: ${project.api_version}
main: github.totorewa.paper.logtps.LogTPSPlugin
database: false
